name: Publish Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Emacs
        run: sudo apt-get install emacs
      - name: Install Org mode
        run: git clone https://github.com/bzg/org-mode && cd org-mode && make autoloads && sudo make install
      - name: Export Org files to HTML
        run: emacs --batch --eval "(require 'org)" --eval "(setq org-html-validation-link nil)" --eval "(org-babel-do-load-languages 'org-babel-load-languages '((shell . t)))" --eval "(setq org-confirm-babel-evaluate nil)" --eval "(mapc (lambda (file) (org-export-to-file (org-export-get-backend 'html) file)) (directory-files \"./\" t \"\\.org$\"))"
      - name: Copy html files to public folder
        run: cp *.html public/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
